### ISSUE TITLE
Not working  after NodeRed Update to 3.0.2 

### ISSUE THREAD

**Issue by YEUAM** [dceejay/node2node#1]
was working fine with NodeRed v1 / v2 .

no error's in Logs , but not working anymore ...

any tips ? 

running NodeRed  on Docker  Image   "nodered/node-red:latest-16"
node-red-contrib-n2n@1.0.0

**Comment by dceejay** [comment]
not off top of my head. Main thing with the node is that it does use multicast and getting that to work with docker can be a pain - so you have to make sure that side is working. I don't use the node with docker so I'm not sure of the tricks to use.

**Comment by YEUAM** [comment]
Upgraded to NodeRed 3.1.0  ,  freshly install  seems to work just fine   
So the problem seems to come with import of my  old stuff ....

Thanx anyway
